### ISSUE TITLE
Essay First Draft

### ISSUE THREAD

**Issue by GreylanLarson** [clearwater-labs/businessOps#15]

**Comment by alex-stout** [comment]
@GreylanLarson Rough draft looks awesome. I added comments on the document for your review. When you make your final edits just let me know and we'll cut the final draft.

**Comment by GreylanLarson** [comment]
Thanks for the edits. I integrated them and left comments on the few that I had questions or comments on. I think we should be able to get it finished within the document except for one that we can discuss when we meet next week. Gonna move the rough draft to the done column ✔️
